"""
CampusEye — backend test suite.

Covers the security- and correctness-critical paths:
  • authentication + role-based access guards
  • séance check-in CODE gate (and that the code never leaks to students)
  • check-in validation guards (active window, already-checked-in, group)
  • attendance integrity / danger-zone aggregation
  • NOVAA intent routing + action role guards (no network — keyword path only)
  • séance code generation

Run:  pytest attendance/tests  (or: python manage.py test attendance)
"""

from datetime import timedelta

from rest_framework.test import APITestCase

from attendance.models import (
    User, Department, Filiere, StudentProfile, TeacherProfile,
    Course, Seance, AttendanceRecord,
    SeanceStatus, generate_seance_code,
)
from attendance.tests.base import BaseData, local_now as _local_now


# ══════════════════════════════════════════════════════════════════════════════
# AUTHENTICATION
# ══════════════════════════════════════════════════════════════════════════════

class AuthTests(BaseData):
    def test_login_returns_tokens(self):
        r = self.client.post("/api/token/", {"username": "stud1", "password": "pass12345"}, format="json")
        self.assertEqual(r.status_code, 200)
        self.assertIn("access", r.data)
        self.assertIn("refresh", r.data)

    def test_login_wrong_password_rejected(self):
        r = self.client.post("/api/token/", {"username": "stud1", "password": "WRONG"}, format="json")
        self.assertEqual(r.status_code, 401)

    def test_me_requires_auth(self):
        self.assertEqual(self.client.get("/api/me/").status_code, 401)

    def test_me_returns_role(self):
        self.client.force_authenticate(user=self.student_user)
        r = self.client.get("/api/me/")
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.data.get("role"), "STUDENT")


# ══════════════════════════════════════════════════════════════════════════════
# ROLE-BASED ACCESS GUARDS
# ══════════════════════════════════════════════════════════════════════════════

class RoleGuardTests(BaseData):
    def test_student_cannot_list_teacher_seances(self):
        self.client.force_authenticate(user=self.student_user)
        r = self.client.get(f"/api/teacher/courses/{self.course.id}/seances/")
        self.assertIn(r.status_code, (401, 403))

    def test_student_cannot_create_seance(self):
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/teacher/courses/{self.course.id}/seances/",
                             {"date": "2030-01-01", "start_time": "10:00"}, format="json")
        self.assertIn(r.status_code, (401, 403))

    def test_teacher_can_list_own_seances(self):
        self.client.force_authenticate(user=self.teacher_user)
        r = self.client.get(f"/api/teacher/courses/{self.course.id}/seances/")
        self.assertEqual(r.status_code, 200)

    def test_teacher_cannot_access_other_teacher_course(self):
        other = User.objects.create_user("teach2", "t2@test.ma", "pass12345", role="TEACHER")
        TeacherProfile.objects.create(user=other, department=self.dept)
        self.client.force_authenticate(user=other)
        r = self.client.get(f"/api/teacher/courses/{self.course.id}/seances/")
        self.assertEqual(r.status_code, 403)

    def test_teacher_cannot_check_in(self):
        s = self._active_seance()
        self.client.force_authenticate(user=self.teacher_user)
        r = self.client.post(f"/api/student/seances/{s.id}/verify-code/", {"code": "ABC123"}, format="json")
        self.assertIn(r.status_code, (401, 403))


# ══════════════════════════════════════════════════════════════════════════════
# SÉANCE CHECK-IN CODE
# ══════════════════════════════════════════════════════════════════════════════

class SeanceCodeTests(BaseData):
    def test_code_autogenerated_on_create(self):
        self.client.force_authenticate(user=self.teacher_user)
        r = self.client.post(f"/api/teacher/courses/{self.course.id}/seances/",
                             {"date": "2030-01-01", "start_time": "10:00"}, format="json")
        self.assertEqual(r.status_code, 201)
        self.assertTrue(r.data[0]["check_in_code"])  # non-empty code returned to teacher

    def test_teacher_supplied_code_used(self):
        self.client.force_authenticate(user=self.teacher_user)
        r = self.client.post(f"/api/teacher/courses/{self.course.id}/seances/",
                             {"date": "2030-01-01", "start_time": "10:00", "check_in_code": "myCode"},
                             format="json")
        self.assertEqual(r.data[0]["check_in_code"], "MYCODE")  # uppercased

    def test_teacher_seance_list_includes_code(self):
        self._active_seance(code="ZZZ999")
        self.client.force_authenticate(user=self.teacher_user)
        r = self.client.get(f"/api/teacher/courses/{self.course.id}/seances/")
        self.assertTrue(any(s.get("check_in_code") == "ZZZ999" for s in r.data))

    def test_student_seance_list_HIDES_code(self):
        self._active_seance(code="SECRET")
        self.client.force_authenticate(user=self.student_user)
        r = self.client.get("/api/student/seances/")
        for s in (r.data if isinstance(r.data, list) else r.data.get("results", [])):
            self.assertNotIn("check_in_code", s)          # code never leaks
            self.assertIn("requires_code", s)             # but the flag is present

    def test_verify_code_correct(self):
        s = self._active_seance(code="GOOD12")
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/student/seances/{s.id}/verify-code/", {"code": "good12"}, format="json")
        self.assertEqual(r.status_code, 200)
        self.assertTrue(r.data["valid"])

    def test_verify_code_wrong(self):
        s = self._active_seance(code="GOOD12")
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/student/seances/{s.id}/verify-code/", {"code": "BAD"}, format="json")
        self.assertEqual(r.status_code, 400)
        self.assertFalse(r.data["valid"])

    def test_checkin_without_code_blocked(self):
        s = self._active_seance(code="NEED11")
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/student/seances/{s.id}/check-in/", {}, format="multipart")
        self.assertEqual(r.status_code, 400)
        self.assertEqual(r.data.get("reason"), "CODE_REQUIRED")

    def test_checkin_wrong_code_blocked(self):
        s = self._active_seance(code="NEED11")
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/student/seances/{s.id}/check-in/", {"code": "NOPE"}, format="multipart")
        self.assertEqual(r.status_code, 400)
        self.assertEqual(r.data.get("reason"), "CODE_INVALID")

    def test_checkin_correct_code_passes_gate(self):
        # Correct code → gate passes → next guard fires (no registered face), proving
        # the code gate let a valid code through.
        s = self._active_seance(code="NEED11")
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/student/seances/{s.id}/check-in/", {"code": "need11"}, format="multipart")
        self.assertEqual(r.data.get("reason"), "NO_REGISTERED_FACE")


# ══════════════════════════════════════════════════════════════════════════════
# CHECK-IN VALIDATION GUARDS
# ══════════════════════════════════════════════════════════════════════════════

class CheckInGuardTests(BaseData):
    def test_checkin_on_completed_seance_rejected(self):
        s = Seance.objects.create(course=self.course, date=_local_now().date(),
                                  start_time=_local_now().time(), status=SeanceStatus.COMPLETED)
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/student/seances/{s.id}/check-in/", {}, format="multipart")
        self.assertEqual(r.status_code, 400)
        self.assertEqual(r.data.get("reason"), "NOT_ACTIVE")

    def test_checkin_already_checked_in(self):
        s = self._active_seance(code="")  # no code → straight to other guards
        AttendanceRecord.objects.create(course=self.course, student=self.student,
                                        seance=s, date=s.date, status="PRESENT")
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post(f"/api/student/seances/{s.id}/check-in/", {}, format="multipart")
        self.assertEqual(r.status_code, 400)
        self.assertEqual(r.data.get("reason"), "ALREADY_CHECKED_IN")

    def test_checkin_missing_seance_404(self):
        self.client.force_authenticate(user=self.student_user)
        r = self.client.post("/api/student/seances/999999/check-in/", {}, format="multipart")
        self.assertEqual(r.status_code, 404)


# ══════════════════════════════════════════════════════════════════════════════
# ATTENDANCE INTEGRITY / DANGER ZONE
# ══════════════════════════════════════════════════════════════════════════════

class AttendanceIntegrityTests(BaseData):
    def _absences(self, n):
        for i in range(n):
            AttendanceRecord.objects.create(course=self.course, student=self.student,
                                            date=_local_now().date() - timedelta(days=i + 1),
                                            status="ABSENT")

    def test_danger_zone_aggregation(self):
        self._absences(3)  # max_absences = 3 → in danger
        from attendance.services.novaa_action_executor import attendance_report
        r = attendance_report(self.admin.id, "ADMIN", filiere="IATE")
        self.assertTrue(r["success"])
        self.assertEqual(r["data"]["danger"], 1)
        self.assertEqual(r["data"]["absent"], 3)

    def test_below_threshold_not_danger(self):
        self._absences(2)  # below 3
        from attendance.services.novaa_action_executor import attendance_report
        r = attendance_report(self.admin.id, "ADMIN", filiere="IATE")
        self.assertEqual(r["data"]["danger"], 0)

    def test_unique_attendance_per_seance(self):
        from django.db import IntegrityError, transaction
        s = self._active_seance()
        AttendanceRecord.objects.create(course=self.course, student=self.student, seance=s,
                                        date=s.date, status="PRESENT")
        with self.assertRaises(IntegrityError):
            with transaction.atomic():
                AttendanceRecord.objects.create(course=self.course, student=self.student, seance=s,
                                                date=s.date, status="ABSENT")


# ══════════════════════════════════════════════════════════════════════════════
# NOVAA — intent routing + action role guards (keyword path, NO network)
# ══════════════════════════════════════════════════════════════════════════════

class NovaaIntentTests(BaseData):
    def test_intent_start_session(self):
        from attendance.services.novaa_tutor_service import detect_intent
        self.assertEqual(detect_intent("démarre la séance de Réseaux", role="TEACHER"), "start_session")

    def test_intent_end_session_conjugation(self):
        from attendance.services.novaa_tutor_service import detect_intent
        self.assertEqual(detect_intent("termine la séance", role="TEACHER"), "end_session")

    def test_intent_enroll_conjugation(self):
        from attendance.services.novaa_tutor_service import detect_intent
        self.assertEqual(detect_intent("inscris hmida dans la filière IATE", role="ADMIN"), "enroll_student")

    def test_intent_attendance_report(self):
        from attendance.services.novaa_tutor_service import detect_intent
        self.assertEqual(detect_intent("rapport de présence de la filière IATE", role="ADMIN"),
                         "attendance_report")

    def test_intent_create_department(self):
        from attendance.services.novaa_tutor_service import detect_intent
        self.assertEqual(detect_intent("crée le département Génie Civil", role="ADMIN"), "create_department")


class NovaaActionGuardTests(BaseData):
    def test_student_cannot_run_teacher_action(self):
        from attendance.services.novaa_action_executor import execute_novaa_action
        r = execute_novaa_action("start_session", {}, self.student_user.id, "STUDENT")
        self.assertFalse(r["success"])

    def test_teacher_cannot_run_admin_action(self):
        from attendance.services.novaa_action_executor import execute_novaa_action
        r = execute_novaa_action("create_department", {"name": "X"}, self.teacher_user.id, "TEACHER")
        self.assertFalse(r["success"])

    def test_admin_create_department(self):
        from attendance.services.novaa_action_executor import execute_novaa_action
        r = execute_novaa_action("create_department", {"name": "Génie Civil", "code": "GC"},
                                 self.admin.id, "ADMIN")
        self.assertTrue(r["success"])
        self.assertTrue(Department.objects.filter(code="GC").exists())

    def test_admin_create_filiere_requires_department(self):
        from attendance.services.novaa_action_executor import execute_novaa_action
        # >1 department exists (GI + one we add) → must specify which
        Department.objects.create(code="GC", name="Génie Civil")
        r = execute_novaa_action("create_filiere", {"name": "NewFil", "code": "NF"},
                                 self.admin.id, "ADMIN")
        self.assertFalse(r["success"])  # ambiguous department


# ══════════════════════════════════════════════════════════════════════════════
# SÉANCE CODE GENERATION
# ══════════════════════════════════════════════════════════════════════════════

class CodeGenTests(APITestCase):
    def test_code_length_and_charset(self):
        for _ in range(50):
            c = generate_seance_code()
            self.assertEqual(len(c), 6)
            self.assertFalse(any(ch in c for ch in "01OI"))  # no ambiguous chars

    def test_codes_are_random(self):
        codes = {generate_seance_code() for _ in range(50)}
        self.assertGreater(len(codes), 40)  # overwhelmingly unique
