# Generated by Django 5.2.12 on 2026-03-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentEmbedding',
            new_name='MaterialEmbedding',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='file_path',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
    ]
