# Generated by Django 5.2.12 on 2026-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_documentembedding_materialembedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to='course_materials/'),
        ),
    ]
