# Generated by Django 5.2.12 on 2026-05-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_notification_type'),
        ('attendance', '0006_seance_system'),
    ]

    operations = [
    ]
