# Generated by Django 5.2.12 on 2026-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_merge_0006_alter_notification_type_0006_seance_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ABSENCE_INFO', 'First absence recorded'), ('ABSENCE_WARNING', 'Approaching absence limit'), ('ABSENCE_DANGER', 'Absence limit reached'), ('MATERIAL_ADDED', 'New course material uploaded'), ('STUDENT_JOINED', 'Student enrolled in your course'), ('COURSE_ASSIGNED', 'You were assigned to a new course'), ('FACE_REQUEST', 'Face registration request update'), ('SEANCE_CREATED', 'New séance scheduled'), ('SEANCE_STARTED', 'Séance has started — mark your attendance')], max_length=30),
        ),
    ]
