# Generated by Django 5.2.12 on 2026-06-05 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_assignment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='massar_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StudentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LEVEL', 'Academic level'), ('STRUGGLE', 'Struggle / weak topic'), ('GOAL', 'Goal / ambition'), ('PREFERENCE', 'Preference'), ('INTEREST', 'Interest'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('fact', models.CharField(max_length=200)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('confidence', models.FloatField(default=0.6)),
                ('mentions', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['-mentions', '-updated_at'],
                'unique_together': {('student', 'key')},
            },
        ),
    ]
