# Generated by Django 5.2.12 on 2026-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_studentprofile_massar_code_studentmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='check_in_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
